services:
  web:
    build:
      context: ./frontend
      target: production
    depends_on: [api]
    restart: unless-stopped
    networks: [default, dokploy-network]

  api:
    build:
      context: ./backend
      target: production
    restart: unless-stopped
    networks: [default, dokploy-network]

networks:
  dokploy-network:
    external: true